[tools]
node = "24.14.1"

[tasks.yarn]
run = "yarn install --immutable"

[tasks.build]
depends = "yarn"
run = "yarn build"

[tasks.typedoc]
depends = "build"
run = "yarn typedoc"

[tasks."checks:lint"]
depends = "yarn"
run = "yarn lint --max-warnings=0"

[tasks."checks:format"]
depends = "yarn"
run = "yarn format-check"

[tasks."checks:barrel"]
description = "Check if barrel files are up-to-date"
depends = "yarn"
run = ["yarn ctix", '[ -z "$(git status --porcelain)" ]']

[tasks."checks:unit"]
depends = "yarn"
run = "yarn test --coverage"

[tasks."checks:integration"]
depends = "yarn"
run = "yarn integration --coverage"

[tasks.ci]
run = { task = "checks:*" }

[settings]
experimental = true # needed for postinstall hook

[hooks]
postinstall = [
  # Enable yarn shim.  Version controlled by package.json#packageManager
  # NOTE: mise can install yarn directly, but renovate does not use mise, so we
  # control yarn versions using the packageManager field.
  "corepack enable yarn",
]
