version: '2'
services:
  redis:
    image: redis@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    ports:
      - '${PGPORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'

volumes:
  postgres_data: {}
  redis_data: {}
