version: '2'
services:
  redis:
    image: redis@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    ports:
      - '${PGPORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'

volumes:
  postgres_data: {}
  redis_data: {}
