version: '2'
services:
  redis:
    image: redis@sha256:0a972391db0b24ec336e35d1bc98b237237e26f82bf5120cf2f6b1688d1df973
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    ports:
      - '${PGPORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'

volumes:
  postgres_data: {}
  redis_data: {}
